version: '3.4'

networks:
    net:

services:

    pelican:
      image:  nginx
      container_name: pelican-nginx
      restart: 'no'
      hostname: pelican-nginx
      volumes:
        - ./src:/var/www/pelican
        - ./nginx:/etc/nginx
      networks:
        net:
          aliases:
            - pelican-nginx
      ports:
        - 80:80
